# Uncomment this line to define a global platform for your project
  platform :ios, '9.1'

target 'TutorMe' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TutorMe
  pod 'SCLAlertView'

  target 'TutorMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TutorMeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
